### PR TITLE
Add custom lambda authorizers to API Gateway implementations

### PR DESCRIPTION
**Pull request by ian-pascoe**
This PR should allow custom lambda authorizers to ApiGatewayV2 and ApiGatewayWebsocket components.

I also included a helper function for the authorizer.

### CODE REVIEW

**Comment by jayair** [comment]
Can you also open an issue for this? I'll have this reviewed.

**Comment by ian-pascoe** [comment]
@jayair Issue sst/sst#4606 applies to this. Let me know if you need me to write up a new one

**Comment by jayair** [comment]
Nah I'll just link to this PR there instead.

**Comment by jayair** [comment]
Thanks!

**Comment by ian-pascoe** [comment]
@fwang - I'm done cleaning this up. Ready for review.

**Comment by ian-pascoe** [comment]
@jayair & @fwang - Any updates here?

**Comment by jayair** [comment]
I'll ping.

**Comment by zammitjames** [comment]
cc @fwang

**Comment by ian-pascoe** [comment]
So it looks like lambda authorizers for API Gateway have been implemented in a different PR, but not for websockets. @jayair should I leave this open for that?

**Comment by jayair** [comment]
Let me check

**Pull request closed without merging**
