### PR TITLE
fix: change Cloudfront Function handler to async function where code injection happens

### PR DESCRIPTION
**Pull request by leoalves**
This Pull Request modifies the Cloudfront function handler to be async in the sections where users can inject custom code. 

This change is necessary to accommodate scenarios where asynchronous operations, such as accessing the Cloudfront KV store or when `await` is required in the user provided code.

### CODE REVIEW

**Comment by paolostyle** [comment]
Thoughts on sst/sst#4126? I believe there will be more cases where the current `injection` pattern will be problematic.

**Comment by leoalves** [comment]
Hello @paolostyle,

Unfornately,  I lack familiarity with the codebase to have an opinion about this. A quick look at the frontend components reveals extensive use of Cloudfront Functions for modifying headers, caching behavior, and other request/response aspects.  I am not sure what would be the unexpected behaviours your suggeston could cause.

IMO, SST should offer the flexibility to pass either the ARN of a CloudFront Function or an object containing the injection code and KV stores.  But again, I am not familiar with the codebase to understand the effects of this change.

It's important to note that this specific PR is unrelated to the decision of how to handle user-provided functions. That decision should be addressed in a separate PR or within the related issue you submitted.

This PR focuses solely on adding `async` to the injection function handler, which appears to be a necessary fix. Since integrating the function with a KV store requires asynchronicity to enable access.

Thanks

**Comment by fwang** [comment]
Thanks @leoalves!

Fixed in https://github.com/sst/ion/commit/2703951f253404f5f1e9afe5b9c82719090b9e1a. Had to change a few places.

Will be in the next release.

**Comment by leoalves** [comment]
Thanks @fwang,

I didn't change in the other places because I didn't think they used the injection pattern and the funciton body didn't have any await calls.  But I think it makes sense to have it everywhere to make it consistent.

I will test when the next release is published.

**Pull request closed without merging**
