### PR TITLE
fix(sst.aws.queue): support contentBasedDeduplication

### PR DESCRIPTION
**Pull request by aryasaatvik**
allows configuring contentBasedDeduplication for FIFO sst.aws.queue

### CODE REVIEW

**Comment by jayair** [comment]
Can you create an issue for this as well?

**Comment by aryasaatvik** [comment]
> Can you create an issue for this as well?

created an issue to discuss passing down pulumi arguments for sst abstractions https://github.com/sst/sst/issues/4048. let me know if you want to keep this as one-off instead

**Comment by aryasaatvik** [comment]
> Can you create an issue for this as well?

created an issue specifically for contentBasedDeduplication https://github.com/sst/sst/issues/4047

**Comment by fwang** [comment]
Thanks @aryasaatvik. Moved `contentBasedDeduplication` inside `fifo`.

**Pull request closed without merging**
