### PR TITLE
remix: derive output directories from vite config

### LINKED ISSUE #670: Remix: static assets are not served with long-term caching
Static assets for a remix deployment are served with the `nonVersionedFilesCacheHeader` and don't benefit from efficient caching.

Bildschirmfoto 2024-07-04 um 17 07 27

This seems to happen because the `assetsVersionedSubDir` isn't set correctly for vite builds of remix. Vite puts the static assets in `build/client/assets`.

Issue for PR #638

### LINKED ISSUE #688: remix deploy fails when using custom `buildDirectory`
Specifying a custom `buildDirectory` ([docs](https://remix.run/docs/en/main/file-conventions/vite-config#builddirectory)) in the `vite.config.ts` for a remix app makes `sst deploy` fail.

**vite.config.js**
```diff
export default defineConfig({
  plugins: [
    remix({
++    buildDirectory: "dist",
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
  ],
});
```

```sh
❯ sst deploy
SST ❍ ion 0.0.503  ready!

➜  App:        remix-aws
   Stage:      clemens

~  Deploying

|  Updated     RemixApp sst:aws:Remix → RemixAppOriginAccessIdentity sst:aws:OriginAccessIdentity
|  Log         Running "npm run build" script
|  Log         > build
|  Log         > remix vite:build
|  Log         vite v5.3.3 building for production...
|  Log         transforming...
|  Log         ✓ 85 modules transformed.
|  Log         rendering chunks...
|  Log         computing gzip size...
|  Log         dist/client/.vite/manifest.json                1.12 kB │ gzip:  0.32 kB
|  Log         dist/client/assets/root-BFUH26ow.css           5.36 kB │ gzip:  1.61 kB
|  Log         dist/client/assets/_index-B6hwyHK-.js          0.94 kB │ gzip:  0.40 kB
|  Log         dist/client/assets/root-Ca5PpFob.js            1.44 kB │ gzip:  0.84 kB
|  Log         dist/client/assets/entry.client-CqMLZIdi.js    4.11 kB │ gzip:  1.56 kB
|  Log         dist/client/assets/jsx-runtime-56DGgGmo.js     8.11 kB │ gzip:  3.05 kB
|  Log         dist/client/assets/components-CPckMTFJ.js    243.44 kB │ gzip: 78.49 kB
|  Log         ✓ built in 618ms
|  Log         vite v5.3.3 building SSR bundle for production...
|  Log         transforming...
|  Log         ✓ 6 modules transformed.
|  Log         rendering chunks...
|  Log         dist/server/.vite/manifest.json               0.22 kB
|  Log         dist/server/assets/server-build-BFUH26ow.css  5.36 kB
|  Log         dist/server/index.js                          7.21 kB
|  Log         ✓ built in 23ms
|  Error       
|  Error: ENOENT: no such file or directory, scandir 'build/client'
|      at Object.readdirSync (node:fs:1507:26)
|      at file:///Users/clemens/Projects/remix-aws/.sst/platform/src/components/aws/remix.ts:431:16
|      at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:404:31
|      at Generator.next (<anonymous>)
|      at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
|      at new Promise (<anonymous>)
|      at __awaiter (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)
|      at applyHelperAsync (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:245:12)
|      at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:316:13
|      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
|    errno: -2,
|    code: 'ENOENT',
|    syscall: 'scandir',
|    path: 'build/client',
|    promise: Promise { <rejected> [Circular *1] }
|  }

×  Failed
   Error: ENOENT: no such file or directory, scandir 'build/client'                                                      
       at Object.readdirSync (node:fs:1507:26)                                                                           
       at file:///Users/clemens/Projects/remix-aws/.sst/platform/src/components/aws/remix.ts:431:16                      
       at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:404:31                          
       at Generator.next (<anonymous>)                                                                                   
       at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71                    
       at new Promise (<anonymous>)                                                                                      
       at __awaiter (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)        
       at applyHelperAsync (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:245:12)
       at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:316:13                          
       at processTicksAndRejections (node:internal/process/task_queues:95:5) {                                           
     errno: -2,                                                                                                          
     code: 'ENOENT',                                                                                                     
     syscall: 'scandir',                                                                                                 
     path: 'build/client',                                                                                               
     promise: Promise { <rejected> [Circular *1] }                                                                       
   }
```

### LINKED ISSUE #4427: remix deploy fails when using custom `buildDirectory`
Specifying a custom `buildDirectory` ([docs](https://remix.run/docs/en/main/file-conventions/vite-config#builddirectory)) in the `vite.config.ts` for a remix app makes `sst deploy` fail.

**vite.config.js**
```diff
export default defineConfig({
  plugins: [
    remix({
++    buildDirectory: "dist",
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true,
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
  ],
});
```

```sh
❯ sst deploy
SST ❍ ion 0.0.503  ready!

➜  App:        remix-aws
   Stage:      clemens

~  Deploying

|  Updated     RemixApp sst:aws:Remix → RemixAppOriginAccessIdentity sst:aws:OriginAccessIdentity
|  Log         Running "npm run build" script
|  Log         > build
|  Log         > remix vite:build
|  Log         vite v5.3.3 building for production...
|  Log         transforming...
|  Log         ✓ 85 modules transformed.
|  Log         rendering chunks...
|  Log         computing gzip size...
|  Log         dist/client/.vite/manifest.json                1.12 kB │ gzip:  0.32 kB
|  Log         dist/client/assets/root-BFUH26ow.css           5.36 kB │ gzip:  1.61 kB
|  Log         dist/client/assets/_index-B6hwyHK-.js          0.94 kB │ gzip:  0.40 kB
|  Log         dist/client/assets/root-Ca5PpFob.js            1.44 kB │ gzip:  0.84 kB
|  Log         dist/client/assets/entry.client-CqMLZIdi.js    4.11 kB │ gzip:  1.56 kB
|  Log         dist/client/assets/jsx-runtime-56DGgGmo.js     8.11 kB │ gzip:  3.05 kB
|  Log         dist/client/assets/components-CPckMTFJ.js    243.44 kB │ gzip: 78.49 kB
|  Log         ✓ built in 618ms
|  Log         vite v5.3.3 building SSR bundle for production...
|  Log         transforming...
|  Log         ✓ 6 modules transformed.
|  Log         rendering chunks...
|  Log         dist/server/.vite/manifest.json               0.22 kB
|  Log         dist/server/assets/server-build-BFUH26ow.css  5.36 kB
|  Log         dist/server/index.js                          7.21 kB
|  Log         ✓ built in 23ms
|  Error       
|  Error: ENOENT: no such file or directory, scandir 'build/client'
|      at Object.readdirSync (node:fs:1507:26)
|      at file:///Users/clemens/Projects/remix-aws/.sst/platform/src/components/aws/remix.ts:431:16
|      at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:404:31
|      at Generator.next (<anonymous>)
|      at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71
|      at new Promise (<anonymous>)
|      at __awaiter (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)
|      at applyHelperAsync (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:245:12)
|      at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:316:13
|      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
|    errno: -2,
|    code: 'ENOENT',
|    syscall: 'scandir',
|    path: 'build/client',
|    promise: Promise { <rejected> [Circular *1] }
|  }

×  Failed
   Error: ENOENT: no such file or directory, scandir 'build/client'                                                      
       at Object.readdirSync (node:fs:1507:26)                                                                           
       at file:///Users/clemens/Projects/remix-aws/.sst/platform/src/components/aws/remix.ts:431:16                      
       at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:404:31                          
       at Generator.next (<anonymous>)                                                                                   
       at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:21:71                    
       at new Promise (<anonymous>)                                                                                      
       at __awaiter (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:17:12)        
       at applyHelperAsync (/Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/pulumi/output.js:245:12)
       at /Users/clemens/Projects/remix-aws/.sst/platform/node_modules/@pulumi/output.ts:316:13                          
       at processTicksAndRejections (node:internal/process/task_queues:95:5) {                                           
     errno: -2,                                                                                                          
     code: 'ENOENT',                                                                                                     
     syscall: 'scandir',                                                                                                 
     path: 'build/client',                                                                                               
     promise: Promise { <rejected> [Circular *1] }                                                                       
   }
```

### LINKED ISSUE #4437: Remix: static assets are not served with long-term caching
Static assets for a remix deployment are served with the `nonVersionedFilesCacheHeader` and don't benefit from efficient caching.

Bildschirmfoto 2024-07-04 um 17 07 27

This seems to happen because the `assetsVersionedSubDir` isn't set correctly for vite builds of remix. Vite puts the static assets in `build/client/assets`.

Issue for PR sst/ion#638

### PR DESCRIPTION
**Pull request by klaemo**
Fixes sst/sst#4437
Fixes sst/sst#4427 
Closes sst/ion#638

This makes the following improvements for remix's vite build:
- detects the remix output directories from the user's vite config. This way we should always get the correct directories, no matter what remix or the user do.
- correctly sets the directory for versioned assets, so we get the correct cache-control headers
- detects`.mts` and `.mjs` versions of the vite config file
- guards against custom values of `serverBuildFile`. We could handle this, if needed.

~~There is a little hack in there to externalize the `vite` import from the esbuild bundle. Otherwise it won't work. I think this should rather be done by defining it as an external package [here](https://github.com/sst/ion/blob/b3a9dcc5cfe05095a25f158c63bf4aa00ad59b24/pkg/js/js.go#L56). But I don't know how to get the whole golang thing including all the JS bits and pieces to build.~~ Fixed this and built the go package.

### CODE REVIEW

**Comment by klaemo** [comment]
Built the go package with `goreleaser build --clean --snapshot --skip validate` and checked `dev` and `deploy` with my snapshot package. I got a working remix deployment using a custom build directory as well as proper cache-control headers on the versioned assets ✅

**Comment by jayair** [comment]
This is helpful, let me tell the team.

**Comment by kyeshmz** [comment]
Would love to see this land!

**Comment by fwang** [comment]
Thanks @klaemo! Real high quality PRs 🧢

**Pull request merged**
