### PR TITLE
api-gateway: add JWT auth

### PR DESCRIPTION
**Pull request by arjunyel**
First time with Pulumi so would like a close review, also how do I best test this? Thank you for SST friends!

### CODE REVIEW

**Comment by fwang** [comment]
Thanks @arjunyel!

Made some changes to the args format. Here's an example - https://ion.sst.dev/docs/component/aws/apigatewayv2/#auth-jwt

**Comment by fwang** [comment]
Released in 0.0.191

**Comment by arjunyel** [comment]
@fwang hey boss, sorry about all the changes you had to make to my code! One thing is I had it my way originally so the auth config would be a discriminated union, meaning typescript would only let you have either jwt or iam, not both

**Comment by fwang** [comment]
yeah, SST v2 used discriminated types. In Ion we decided to move away from it b/c Intellisense suggests fields from all unioned types until the discriminated field is typed out. And that caused some confusion for folks that are new to a component.

**Pull request merged**
