### PR TITLE
Update documentation to warn people about Secret naming requirements

### PR DESCRIPTION
**Pull request by subssn21**
The documentation does not mention the naming requirements for secrets, updating the documentation to reflect the error message you receive with an improperly named secret

### CODE REVIEW

**Comment by jayair** [comment]
Was this an error you got on deploy?

**Comment by subssn21** [comment]
Yes, that was literally the error message you get, but it's not mentioned in the documentation that their are any special requirements for secret names, so I assumed if it was a valid variable name it would work which is not the case.

**Comment by jayair** [comment]
Yeah let me add it to the docs. The secret names follow the same rules as the components.

**Comment by nurulhudaapon** [comment]
@jayair What was that PR about? Underscore in secret name works now.


https://github.com/sst/ion/pull/1073

**Pull request merged**
