### PR TITLE
feat: add component for AnalogJS

### PR DESCRIPTION
**Pull request by brandonroberts**
Adds the component, docs, examples, and template for AnalogJS. Analog is the fullstack meta-framework for Angular, built on top of Vite and Nitro.

This allows you to run `sst init` on an Analog project, develop locally, and deploy to AWS.

### CODE REVIEW

**Comment by jayair** [comment]
Wow that's pretty comprehensive. Thank you!

Let me ask @fwang to review the component and then I'll review the docs and we can merge it.

**Comment by fwang** [comment]
Thanks @brandonroberts! The component looks good.

Ran into two issues while deploying a Analog app:
1. Building Analog app (ie. `npm run build`) seems to have succeeded, but complained could not find module `std-env/` and `marked/`.
Screen Shot 2024-09-21 at 4 41 58 PM

2. `sst deploy` could not find `dist/analog/server/nitro.json`. I only see `dist/analog/nitro.json`.
Screen Shot 2024-09-21 at 4 46 32 PM

**Comment by brandonroberts** [comment]
Thanks @fwang. I pushed up a path fix for the `nitro.json`. 

The first message is something we've seen before, but it doesn't affect the deployed application.

**Comment by fwang** [comment]
Awesome!

Released in v3.1.32

**Comment by brandonroberts** [comment]
Thanks!

**Pull request merged**
