### PR TITLE
feat: include pothos graphql example for aws

### PR DESCRIPTION
**Pull request by joegearlesss**
This PR adds a new example of pothos graphql for aws

Based on https://pothos-graphql.dev/

Please let me know if you have any questions!

### CODE REVIEW

**Comment by jbrown** [comment]
@joegearlesss what about the build command from v2? Curious if you found a way to incorporate that in Ion..

```javascript
pothos: {
  schema: "packages/functions/src/graphql/schema.ts",
  output: "packages/graphql/schema.graphql",
  commands: [
    "cd packages/graphql && npx @genql/cli --output ./genql --schema ./schema.graphql --esm",
  ],
}
```

**Comment by jayair** [comment]
Thanks! Will review soon.

**Comment by joegearlesss** [comment]
> @joegearlesss what about the build command from v2? Curious if you found a way to incorporate that in Ion..
> 
> ```js
> pothos: {
>   schema: "packages/functions/src/graphql/schema.ts",
>   output: "packages/graphql/schema.graphql",
>   commands: [
>     "cd packages/graphql && npx @genql/cli --output ./genql --schema ./schema.graphql --esm",
>   ],
> }
> ```

@jbrown Thank you for question. Working on pothos component for aws. Will make other pr soon

**Comment by joegearlesss** [comment]
@jbrown If I understand ion concept correctly, schema extraction and other genql/cli like generations is out of ion scope. 
Than is why I not create PothosGraphql component for sst domain and made it separately (like drizzle-kit).

You could use it like below

1. Start sst local server by `sst dev`
2. Start pothos schema generator (with watching) in other terminal by `npm run extract:dev`. Or you could use one time extraction by `npm run extraction`

I add client usage example in `client.ts`
 
@jayair  Tell me if I misunderstood ion concept

**Comment by zammitjames** [comment]
@joegearlesss my two cents: I think it would be ideal if the sst local server handled generating the `schema.gql` file for you so developers don't need to run and maintain a separate terminal process.

**Comment by jbrown** [comment]
> @joegearlesss my two cents: I think it would be ideal if the sst local server handled generating the `schema.gql` file for you so developers don't need to run and maintain a separate terminal process.

Agree, this would reach parity with how v2 worked. But I don't think the logic should be where it was in v2, perhaps something more generic instead of having a pothos key within the component definition. I'm sure there's other similar build processes that need the same and I agree it would be nice not to have a separate terminal process.

**Comment by sb55555** [comment]
good job @joegearlesss 

you've used the new [sst shell](https://sst.dev/docs/reference/cli/#shell) very elegantly to port this to v3

it has been working on my side running the command aside of sst multiplexer to watch files and extract the schema

a specific pothos-graphql sst construct on top of apigatewayv2 or function would be helpful to have a better integration of the schema extractor with sst multiplexer in dev and deploy for perfect DX like the nextjs one automatically starts nextjs in dev and deploy in prod

happy to see pothos-graphql integration coming to v3 very soon

**Comment by joegearlesss** [comment]
@joegearlesss already made pothos graphgl component with multiplexer support. Testing dev function for regenerate on file changes. Will finish it on next week

**Comment by joegearlesss** [comment]
> good job @joegearlesss
> 
> you've used the new [sst shell](https://sst.dev/docs/reference/cli/#shell) very elegantly to port this to v3
> 
> it has been working on my side running the command aside of sst multiplexer to watch files and extract the schema
> 
> a specific pothos-graphql sst construct on top of apigatewayv2 or function would be helpful to have a better integration of the schema extractor with sst multiplexer in dev and deploy for perfect DX like the nextjs one automatically starts nextjs in dev and deploy in prod
> 
> happy to see pothos-graphql integration coming to v3 very soon

@sb55555 already made pothos graphgl component with multiplexer support. Testing dev function for regenerate on file changes. Will finish it on next week

**Comment by fwang** [comment]
@joegearlesss thanks for putting the example together.

we are moving `sst/ion -> sst/sst` and unfortunately this is going to be a messy process because of github's limitations

i'm going to close this PR for now and it can be re-opened in the new `sst/sst` repo that will be ready in the next few days

**Pull request closed without merging**
