### PR TITLE
Update Pulumi to v3.126.0

### PR DESCRIPTION
**Pull request by mlafeldt**
To benefit from https://github.com/pulumi/pulumi/pull/16575 and other fixes.

What I did:

```console
❯ go get github.com/pulumi/pulumi/sdk/v3
go: upgraded github.com/pulumi/esc v0.8.3 => v0.9.1
go: upgraded github.com/pulumi/pulumi/sdk/v3 v3.115.2 => v3.124.0
go: upgraded golang.org/x/crypto v0.22.0 => v0.24.0
go: upgraded golang.org/x/exp v0.0.0-20240325151524-a685a6edb6d8 => v0.0.0-20240604190554-fc45aab8b7f8
go: upgraded golang.org/x/mod v0.16.0 => v0.18.0
go: upgraded golang.org/x/net v0.23.0 => v0.26.0
go: upgraded golang.org/x/sync v0.6.0 => v0.7.0
go: upgraded golang.org/x/sys v0.20.0 => v0.21.0
go: upgraded golang.org/x/term v0.19.0 => v0.21.0
go: upgraded golang.org/x/text v0.15.0 => v0.16.0
go: upgraded golang.org/x/tools v0.19.0 => v0.22.0

❯ go mod tidy
go: downloading github.com/aaronjanse/3mux v1.1.0
go: downloading github.com/creack/pty v1.1.21
go: downloading github.com/charmbracelet/x/xpty v0.1.0
go: downloading github.com/charmbracelet/x/termios v0.1.0
go: downloading github.com/charmbracelet/x/conpty v0.1.0
go: downloading github.com/charmbracelet/x/term v0.1.0
go: downloading github.com/charmbracelet/x/errors v0.0.0-20240508181413-e8d8b6e2de86
go: downloading github.com/charmbracelet/x/input v0.1.0
go: downloading github.com/charmbracelet/x/windows v0.1.0
go: downloading github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e
go: downloading github.com/erikgeiser/coninput v0.0.0-20211004153227-1c3628e74d0f
```

### CODE REVIEW

**Comment by thdxr** [comment]
also need to bump this: https://github.com/sst/ion/blob/dev/pkg/global/global.go#L18

**Comment by mlafeldt** [comment]
@thdxr done

**Comment by mlafeldt** [comment]
Rebased after #678 got merged

**Comment by thdxr** [comment]
sorry have some conflicts do you mind fixing

**Comment by mlafeldt** [comment]
@thdxr Done. In the meantime, Pulumi had another release. Updated the PR accordingly.

**Comment by abnud11** [comment]
The problem with updating pulumi to v3.126(or 3.127) makes many dynamic resources unserializable, I already tried updating pulumi and many serialization errors occured.

I think we need to test further with the latest version of pulumi
@thdxr

**Comment by mlafeldt** [comment]
@abnud11 Interesting. What would be examples of such resources?

**Comment by abnud11** [comment]
> @abnud11 Interesting. What would be examples of such resources?

The resources I knew of:
`OriginAccessIdentity` in `platform/src/aws/providers/origin-access-identity.ts`
`FunctionCodeUpdater` in `platform/src/aws/providers/function-code-updater.ts`

Those I know of, not sure about the others.
The `FunctionCodeUpdater` in particular seems crucial since it's responsible for updating Lambda Functions code

**Comment by abnud11** [comment]
the `OriginAcessIdentity` throws `Unexpected missing variable in closure: input`, the other one I remember the same message just with different missing variable(don't remember the name of the missing variable).

**Comment by mlafeldt** [comment]
Pulumi was updated in https://github.com/sst/ion/commit/33637d5774c53e8444f1fd2664331817b03ab06b a few days ago.

**Pull request closed without merging**
