### PR TITLE
Rust Example using https://loco.rs

### PR DESCRIPTION
**Pull request by rvcas**
I am almost there with a rust example using the "rails" of rust.

The only issue I am having at this point is the domain mapping keeps returning a 502, I'm not exactly sure what the issue is atm. I believe the application is configured correctly but maybe I'm wrong. 

Also, I think to have the `just dev` command work, I will need to setup a bastion server but I haven't gotten around to playing with that yet.

@jondot this is what I DM'd you about the other day. I think this would be a good example and blog post for the loco community, any insight into what I might be misconfiguring would be awesome.

last attempted with sst `v3.1.32`

### CODE REVIEW

**Comment by jondot** [comment]
Thanks for pinging me here! I'm having a look 👍

**Comment by jondot** [comment]
I'm not sure this is a subdomain mapping causing the issue, but it may be something with how the app starts and its environment.
Do you have some logs you can share here?

**Comment by rvcas** [comment]
@jondot so according to the logs I get the typical print out of all the routes, then the usual loco ascii art, and finally `listening on localhost:5150`

```

September 25, 2024 at 17:46 (UTC-4:00) | {"timestamp":"2024-09-25T21:46:52.563366Z","level":"INFO","fields":{"message":"[POST] /auth/reset"},"target":"loco_rs::controller::app_routes"} | - | -
-- | -- | -- | --
September 25, 2024 at 17:46 (UTC-4:00) | {"timestamp":"2024-09-25T21:46:52.563378Z","level":"INFO","fields":{"message":"[GET] /user/current"},"target":"loco_rs::controller::app_routes"} | - | -
September 25, 2024 at 17:46 (UTC-4:00) | {"timestamp":"2024-09-25T21:46:52.563406Z","level":"INFO","fields":{"message":"[Middleware] +etag"},"target":"loco_rs::controller::app_routes"} | - | -
September 25, 2024 at 17:46 (UTC-4:00) | {"timestamp":"2024-09-25T21:46:52.563476Z","level":"INFO","fields":{"message":"[Middleware] +limit payload","data":"5mb"},"target":"loco_rs::controller::app_routes"} | - | -
September 25, 2024 at 17:46 (UTC-4:00) | {"timestamp":"2024-09-25T21:46:52.563578Z","level":"INFO","fields":{"message":"[Middleware] +log trace id"},"target":"loco_rs::controller::app_routes"} | - | -
September 25, 2024 at 17:46 (UTC-4:00) | {"timestamp":"2024-09-25T21:46:52.563774Z","level":"INFO","fields":{"message":"[Middleware] +secure headers"},"target":"loco_rs::controller::app_routes"} | - | -
September 25, 2024 at 17:46 (UTC-4:00) | {"timestamp":"2024-09-25T21:46:52.563815Z","level":"INFO","fields":{"message":"[Middleware] +request id"},"target":"loco_rs::controller::app_routes"} | - | -
September 25, 2024 at 17:46 (UTC-4:00) |   | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▄ ▀ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▀ ▄ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▄ ▀ ▄ ▄ ▄▀ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▄ ▀▄▄ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▄ ▀ ▀ ▀▄▀█▄ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▀█▄ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄▄▄ ▀▀█ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ██████ █████ ███ █████ ███ █████ ███ ▀█ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ██████ █████ ███ █████ ▀▀▀ █████ ███ ▄█▄ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ██████ █████ ███ █████ █████ ███ ████▄ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ██████ █████ ███ █████ ▄▄▄ █████ ███ █████ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ██████ █████ ███ ████ ███ █████ ███ ████▀ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▀▀▀██▄ ▀▀▀▀▀▀▀▀▀▀ ▀▀▀▀▀▀▀▀▀▀ ▀▀▀▀▀▀▀▀▀▀ ██▀ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀ | - | -
September 25, 2024 at 17:46 (UTC-4:00) | https://loco.rs | - | -
September 25, 2024 at 17:46 (UTC-4:00) |   | - | -
September 25, 2024 at 17:46 (UTC-4:00) | environment: [32mdevelopment[0m | - | -
September 25, 2024 at 17:46 (UTC-4:00) | logger: [32minfo[0m | - | -
September 25, 2024 at 17:46 (UTC-4:00) | compilation: [32mrelease[0m | - | -
September 25, 2024 at 17:46 (UTC-4:00) | modes: [32mserver[0m | - | -
September 25, 2024 at 17:46 (UTC-4:00) |   | - | -
September 25, 2024 at 17:46 (UTC-4:00) | listening on [32mlocalhost[0m:[32m5150[0m

**Comment by thdxr** [comment]
@jondot do you know how to specify it should listen on 0.0.0.0 and not localhost

**Comment by jondot** [comment]
Yes just with the -b flag

**Pull request closed without merging**
