### PR TITLE
fix(docs): Minor typos

### PR DESCRIPTION
**Pull request by garretcharp**

### CODE REVIEW

**Comment by garretcharp** [comment]
While `it'll` is not a typo it read weirdly to me so I changed it.

**Comment by jayair** [comment]
Yeah some of these are generated. Left a link to their source, make the change there and resubmit?

Don't worry about the generated files, it'll get overwritten on deploy.

**Comment by garretcharp** [comment]
Should be fixed in the places it gets generated from now @jayair

**Comment by jayair** [comment]
Thanks!

**Pull request merged**
