### PR TITLE
fix: change arch to arm64 if the machine is aarch64

### LINKED ISSUE #380: Install script fails on machines with aarch architecture
There is not binary in the releases for `aarch64` so the install scripts fails to download a zip. `aarch64` is the same as `arm64` so the script just needs to change `arch` to `arm64` if it equals `aarch64`.

image

### LINKED ISSUE #4656: Install script fails on machines with aarch architecture
There is not binary in the releases for `aarch64` so the install scripts fails to download a zip. `aarch64` is the same as `arm64` so the script just needs to change `arch` to `arm64` if it equals `aarch64`.

image

### PR DESCRIPTION
**Pull request by lukeshay**
Fixes sst/sst#4656 

image

### CODE REVIEW

**Comment by jayair** [comment]
Is there a related issue for this?

So we can assign that and have this reviewed.

**Comment by lukeshay** [comment]
> Is there a related issue for this?
> 
> 
> 
> So we can assign that and have this reviewed.

No but I can create one

**Comment by qw-in** [comment]
Looks similar to sst/ion#155

**Comment by thdxr** [comment]
we merged the other one!

**Pull request closed without merging**
